spring.application.name=ssl
server.port=7443
server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=password
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2
server.ssl.ciphers=TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA


openidconnect.endpoint=https://localhost:10443
openidconnect.clientId=4d2af6f964ed1208a49f
openidconnect.clientSecret=9fd2b6469f84a9880e9c65a2aff101fe25b7866c

websocket.endpoint=wss://localhost:7443/coins