// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TickerUpdate.proto
// Protobuf Java Version: 4.31.0

package com.example.protobuf;

public final class TickerUpdateOuterClass {
  private TickerUpdateOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      TickerUpdateOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.example.protobuf.Coin}
   */
  public enum Coin
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BTC = 0;</code>
     */
    BTC(0),
    /**
     * <code>ETH = 1;</code>
     */
    ETH(1),
    /**
     * <code>XRP = 2;</code>
     */
    XRP(2),
    /**
     * <code>DOGE = 3;</code>
     */
    DOGE(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        Coin.class.getName());
    }
    /**
     * <code>BTC = 0;</code>
     */
    public static final int BTC_VALUE = 0;
    /**
     * <code>ETH = 1;</code>
     */
    public static final int ETH_VALUE = 1;
    /**
     * <code>XRP = 2;</code>
     */
    public static final int XRP_VALUE = 2;
    /**
     * <code>DOGE = 3;</code>
     */
    public static final int DOGE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Coin valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Coin forNumber(int value) {
      switch (value) {
        case 0: return BTC;
        case 1: return ETH;
        case 2: return XRP;
        case 3: return DOGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Coin>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Coin> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Coin>() {
            public Coin findValueByNumber(int number) {
              return Coin.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.protobuf.TickerUpdateOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Coin[] VALUES = values();

    public static Coin valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Coin(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.example.protobuf.Coin)
  }

  public interface TickerUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.protobuf.TickerUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.example.protobuf.Coin coin = 1;</code>
     * @return The enum numeric value on the wire for coin.
     */
    int getCoinValue();
    /**
     * <code>.com.example.protobuf.Coin coin = 1;</code>
     * @return The coin.
     */
    com.example.protobuf.TickerUpdateOuterClass.Coin getCoin();

    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.example.protobuf.TickerUpdate}
   */
  public static final class TickerUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.protobuf.TickerUpdate)
      TickerUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        TickerUpdate.class.getName());
    }
    // Use TickerUpdate.newBuilder() to construct.
    private TickerUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TickerUpdate() {
      coin_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.TickerUpdateOuterClass.internal_static_com_example_protobuf_TickerUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.TickerUpdateOuterClass.internal_static_com_example_protobuf_TickerUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.class, com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.Builder.class);
    }

    public static final int COIN_FIELD_NUMBER = 1;
    private int coin_ = 0;
    /**
     * <code>.com.example.protobuf.Coin coin = 1;</code>
     * @return The enum numeric value on the wire for coin.
     */
    @java.lang.Override public int getCoinValue() {
      return coin_;
    }
    /**
     * <code>.com.example.protobuf.Coin coin = 1;</code>
     * @return The coin.
     */
    @java.lang.Override public com.example.protobuf.TickerUpdateOuterClass.Coin getCoin() {
      com.example.protobuf.TickerUpdateOuterClass.Coin result = com.example.protobuf.TickerUpdateOuterClass.Coin.forNumber(coin_);
      return result == null ? com.example.protobuf.TickerUpdateOuterClass.Coin.UNRECOGNIZED : result;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_ = 0D;
    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (coin_ != com.example.protobuf.TickerUpdateOuterClass.Coin.BTC.getNumber()) {
        output.writeEnum(1, coin_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(2, price_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (coin_ != com.example.protobuf.TickerUpdateOuterClass.Coin.BTC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, coin_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.TickerUpdateOuterClass.TickerUpdate)) {
        return super.equals(obj);
      }
      com.example.protobuf.TickerUpdateOuterClass.TickerUpdate other = (com.example.protobuf.TickerUpdateOuterClass.TickerUpdate) obj;

      if (coin_ != other.coin_) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COIN_FIELD_NUMBER;
      hash = (53 * hash) + coin_;
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.TickerUpdateOuterClass.TickerUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.protobuf.TickerUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.protobuf.TickerUpdate)
        com.example.protobuf.TickerUpdateOuterClass.TickerUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.TickerUpdateOuterClass.internal_static_com_example_protobuf_TickerUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.TickerUpdateOuterClass.internal_static_com_example_protobuf_TickerUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.class, com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.Builder.class);
      }

      // Construct using com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        coin_ = 0;
        price_ = 0D;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.TickerUpdateOuterClass.internal_static_com_example_protobuf_TickerUpdate_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.TickerUpdateOuterClass.TickerUpdate getDefaultInstanceForType() {
        return com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.TickerUpdateOuterClass.TickerUpdate build() {
        com.example.protobuf.TickerUpdateOuterClass.TickerUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.TickerUpdateOuterClass.TickerUpdate buildPartial() {
        com.example.protobuf.TickerUpdateOuterClass.TickerUpdate result = new com.example.protobuf.TickerUpdateOuterClass.TickerUpdate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.TickerUpdateOuterClass.TickerUpdate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.coin_ = coin_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.TickerUpdateOuterClass.TickerUpdate) {
          return mergeFrom((com.example.protobuf.TickerUpdateOuterClass.TickerUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.TickerUpdateOuterClass.TickerUpdate other) {
        if (other == com.example.protobuf.TickerUpdateOuterClass.TickerUpdate.getDefaultInstance()) return this;
        if (other.coin_ != 0) {
          setCoinValue(other.getCoinValue());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getPrice()) != 0) {
          setPrice(other.getPrice());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                coin_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 24: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int coin_ = 0;
      /**
       * <code>.com.example.protobuf.Coin coin = 1;</code>
       * @return The enum numeric value on the wire for coin.
       */
      @java.lang.Override public int getCoinValue() {
        return coin_;
      }
      /**
       * <code>.com.example.protobuf.Coin coin = 1;</code>
       * @param value The enum numeric value on the wire for coin to set.
       * @return This builder for chaining.
       */
      public Builder setCoinValue(int value) {
        coin_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.example.protobuf.Coin coin = 1;</code>
       * @return The coin.
       */
      @java.lang.Override
      public com.example.protobuf.TickerUpdateOuterClass.Coin getCoin() {
        com.example.protobuf.TickerUpdateOuterClass.Coin result = com.example.protobuf.TickerUpdateOuterClass.Coin.forNumber(coin_);
        return result == null ? com.example.protobuf.TickerUpdateOuterClass.Coin.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.example.protobuf.Coin coin = 1;</code>
       * @param value The coin to set.
       * @return This builder for chaining.
       */
      public Builder setCoin(com.example.protobuf.TickerUpdateOuterClass.Coin value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000001;
        coin_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.example.protobuf.Coin coin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        coin_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 2;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 2;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {

        price_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.protobuf.TickerUpdate)
    }

    // @@protoc_insertion_point(class_scope:com.example.protobuf.TickerUpdate)
    private static final com.example.protobuf.TickerUpdateOuterClass.TickerUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.TickerUpdateOuterClass.TickerUpdate();
    }

    public static com.example.protobuf.TickerUpdateOuterClass.TickerUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TickerUpdate>
        PARSER = new com.google.protobuf.AbstractParser<TickerUpdate>() {
      @java.lang.Override
      public TickerUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TickerUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TickerUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.TickerUpdateOuterClass.TickerUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_protobuf_TickerUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_protobuf_TickerUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TickerUpdate.proto\022\024com.example.protob" +
      "uf\"Z\n\014TickerUpdate\022(\n\004coin\030\001 \001(\0162\032.com.e" +
      "xample.protobuf.Coin\022\r\n\005price\030\002 \001(\001\022\021\n\tt" +
      "imestamp\030\003 \001(\003*+\n\004Coin\022\007\n\003BTC\020\000\022\007\n\003ETH\020\001" +
      "\022\007\n\003XRP\020\002\022\010\n\004DOGE\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_protobuf_TickerUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_protobuf_TickerUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_protobuf_TickerUpdate_descriptor,
        new java.lang.String[] { "Coin", "Price", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
